BÀI TRÊN LỚP

In [ ]:
import numpy as np
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])
x = 2*u-(v+3*w)
print (x)

[ 18 -11   9  -8]


In [ ]:
import numpy as np
u = np.array([2, -1, 5, 0])
v = np.array([4, 3, 1, -1])
w = np.array([-6, 2, 0, 3])
x = u - 0.5 * v - 1.5 * w
print(x)


[ 9.  -5.5  4.5 -4. ]


In [ ]:
from numpy import linalg
A = np.matrix([[0, -1, 3],[1, 1, 1],[4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print (X)

[ 1. -2. -1.]


In [ ]:
from numpy import linalg as LA
A = np.matrix([[1,0],[0,0]])
B = np.matrix([[0,0],[0,1]])
LA.inv(A)

LinAlgError: Singular matrix

In [ ]:
 LA.inv(B)

LinAlgError: Singular matrix

In [ ]:
LA.inv(A+B)

matrix([[1., 0.],
        [0., 1.]])

In [ ]:
LA.det(A)

np.float64(0.0)

In [ ]:
LA.det(B)

np.float64(0.0)

In [ ]:
LA.det(A+B)

np.float64(1.0)

In [ ]:
import sympy as sp
x, y = sp.symbols('x y')
A = sp.Matrix([[x, y],[y, x]])
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1],[y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])
A1.T

Matrix([
[x1, y1],
[y1, x1]])

In [ ]:
(A1+A2).T

Matrix([
[x1 + x2, y1 + y2],
[y1 + y2, x1 + x2]])

In [ ]:
((A1+A2).T).equals(A1+A2)

True

In [ ]:
c = sp.symbols('c')
print (c*A)

Matrix([[c*x, c*y], [c*y, c*x]])


In [ ]:
 ((c*A).T).equals(c*A)

True

In [ ]:
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([0, 1, 2])
v3 = np.array([-1, 0, 1])
w1 = np.array([1, 1, 1])
A = np.column_stack((v1, v2, v3))
try:
    c = np.linalg.solve(A, w1)
    print("a. w1 là tổ hợp tuyến tính của v1, v2, v3 với hệ số:", c)
except np.linalg.LinAlgError:
    print("a. w1 không là tổ hợp tuyến tính của v1, v2, v3")

a. w1 là tổ hợp tuyến tính của v1, v2, v3 với hệ số: [ 5.00000000e-01 -1.66533454e-16 -5.00000000e-01]


In [ ]:
w2 = np.array([1, -2, 2])
try:
    c = np.linalg.solve(A, w2)
    print("b. w2 là tổ hợp tuyến tính của v1, v2, v3 với hệ số:", c)
except np.linalg.LinAlgError:
    print("b. w2 không là tổ hợp tuyến tính của v1, v2, v3")

b. w2 là tổ hợp tuyến tính của v1, v2, v3 với hệ số: [ 3.15251974e+16 -6.30503948e+16  3.15251974e+16]


In [ ]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1-2*c3, 2*c1+c2, 3*c1+2*c2+c3], [c1, c2, c3])

{c1: 0, c2: 0, c3: 0}

In [ ]:
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: u1/2 + u2/2, c2: u1/2 - u2/2}

In [ ]:
u1 = 0
u2 = 0
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: 0, c2: 0}

In [ ]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])
P_caua = (P.T + vecdelta).T
print (P_caua)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


In [ ]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0],
                           [0.0, 2.0]])
P_caub = (P.T @ matran_biendoi + vecdelta).T
print (P_caub)

[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [ ]:
import numpy as np
def transform_point(x, y, a, b):
    M = np.array([
        [-1, 0],
        [ 0, 1]
    ])
    P = np.array([x, y])
    T = np.array([a, b])
    new_point = M @ P + T
    return new_point
x, y = 3, 2
a, b = 5, -1
new_x, new_y = transform_point(x, y, a, b)
print(f"Điểm sau biến đổi: ({new_x}, {new_y})")

Điểm sau biến đổi: (2, 1)


In [ ]:
import numpy as np
def shear_translate_point(x, y, p, q, a, b):
    M = np.array([
        [1, p],
        [q, 1]])
    P = np.array([x, y])
    T = np.array([a, b])
    new_point = M @ P + T
    return new_point
x, y = 3, 2
p, q = 0.5, 0
a, b = 1, -1
new_x, new_y = shear_translate_point(x, y, p, q, a, b)
print(f"Điểm sau biến đổi: ({new_x}, {new_y})")

Điểm sau biến đổi: (5.0, 1.0)


In [ ]:
import numpy as np
def reflect_y0(x, y):
    M = np.array([
        [-1, 0],
        [ 0, 1]
    ])
    P = np.array([x, y])
    new_point = M @ P
    return new_point
x, y = 3, 2
new_x, new_y = reflect_y0(x, y)
print(f"Đối xứng qua y=0: ({new_x}, {new_y})")

Đối xứng qua y=0: (-3, 2)


In [ ]:
def reflect_y_eq_x(x, y):
    M = np.array([
        [0, 1],
        [1, 0]])
    P = np.array([x, y])
    new_point = M @ P
    return new_point
new_x, new_y = reflect_y_eq_x(x, y)
print(f"Đối xứng qua y=x: ({new_x}, {new_y})")

Đối xứng qua y=x: (2, 3)


In [ ]:
import sympy as sp
from sympy import lambdify
x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')
a, b, c = sp.symbols('a b c') # khai báo thêm 3 biến a, b, c giả định X = (a, b, c)
d, e, f = sp.symbols('d e f') # khai báo thêm 3 biến d, e, f giả định Y = (e, d, f)
f1(a, b, c)

a - b + c

In [ ]:
f1(d, e, f)

d - e + f

In [ ]:
f1(a+d, b+e, c+f)

a - b + c + d - e + f

In [ ]:
f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f)

True

In [ ]:
(f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f))

True

In [ ]:
q = sp.symbols('q')
(q*f1(a,b,c) + f1(d,e,f)).equals(f1(q*a+d, q*b+e, q*c+f).expand())

True

In [ ]:
bieuthuc2 = 2*x2 + 3* x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'numpy')
(q*f2(a,b,c) + f2(d,e,f)).equals(f2(q*a+d, q*b+e, q*c+f).expand())

In [38]:
import numpy as np
u1 = np.array([1,2])
u2 = np.array([3,5])
u3 = np.array([4,5])
A = np.column_stack((u1, u2))
b = u3
alpha_beta = np.linalg.solve(A, b)
alpha, beta = alpha_beta
print(f"alpha = {alpha}, beta = {beta}")
f_u1 = np.array([1,1,2])
f_u2 = np.array([4,2,1])
f_u3 = alpha * f_u1 + beta * f_u2
print(f"f(4,5) = {f_u3}")

alpha = -5.0, beta = 3.0
f(4,5) = [ 7.  1. -7.]


In [37]:
import sympy as sp
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
sp.solve([a+3*b-x, 2*a+5*b-y],[a,b])

{a: -5*x + 3*y, b: 2*x - y}

In [42]:
import numpy as np
u1 = np.array([1, 2])
u2 = np.array([3, 5])
u3 = np.array([4, 5])
A = np.column_stack((u1, u2))
b = u3
alpha_beta = np.linalg.solve(A, b)
alpha, beta = alpha_beta
print(f"α = {alpha}, β = {beta}")
f_u1 = np.array([1, 1, 2])
f_u2 = np.array([4, 2, 1])
f_u3 = alpha * f_u1 + beta * f_u2
print(f"f(u3) = {f_u3}")

α = -5.0, β = 3.0
f(u3) = [ 7.  1. -7.]


In [43]:
import numpy as np
u1 = np.array([-1, 1])
u2 = np.array([1, 0])
v1 = np.array([1, 2])
v2 = np.array([1, 3])
def f(x):
    return np.array([x[0] - x[1], x[0]])
fu1 = f(u1)
fu2 = f(u2)
F = np.column_stack((v1, v2))
coords_fu1 = np.linalg.solve(F, fu1)
coords_fu2 = np.linalg.solve(F, fu2)
A = np.column_stack((coords_fu1, coords_fu2))
print("Tọa độ [f(u1)]_F:", coords_fu1)
print("Tọa độ [f(u2)]_F:", coords_fu2)
print("Ma trận ánh xạ A = [f]^F_B:\n", A)

Tọa độ [f(u1)]_F: [-5.  3.]
Tọa độ [f(u2)]_F: [ 2. -1.]
Ma trận ánh xạ A = [f]^F_B:
 [[-5.  2.]
 [ 3. -1.]]


In [44]:
import numpy as np
A, B, C, D, E, F = 5, -6, 5, 14*np.sqrt(2), -2*np.sqrt(2), 18
theta = -np.pi / 4
cos_t = np.cos(theta)
sin_t = np.sin(theta)
R = np.array([[cos_t, -sin_t],
              [sin_t, cos_t]])
print("Ma trận xoay R:")
print(R)
Q = np.array([[A, B/2],
              [B/2, C]])
print("Ma trận Q (x, y):")
print(Q)
Q_prime = R.T @ Q @ R
print("Ma trận Q' sau xoay:")
print(Q_prime)
A_prime, C_prime = Q_prime[0,0], Q_prime[1,1]
B_prime = 2 * Q_prime[0,1]
print(f"A' = {A_prime}, B' = {B_prime}, C' = {C_prime}")

Ma trận xoay R:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
Ma trận Q (x, y):
[[ 5. -3.]
 [-3.  5.]]
Ma trận Q' sau xoay:
[[ 8.00000000e+00 -8.07006129e-16]
 [-4.69783081e-16  2.00000000e+00]]
A' = 7.999999999999999, B' = -1.614012257679138e-15, C' = 1.9999999999999998


BT VỀ NHÀ

In [46]:
import sympy as sp
def g(x, y, z):
    return (x + y, z + 2, 0)
u = sp.Matrix([1, 2, 3])
v = sp.Matrix([4, 5, 6])
c = 3
g_u = sp.Matrix(g(*u))
g_v = sp.Matrix(g(*v))
g_u_plus_v = sp.Matrix(g(*(u + v)))
g_u_plus_g_v = g_u + g_v
g_cu = sp.Matrix(g(*(c * u)))
c_g_u = c * g_u
print("g(u + v) == g(u) + g(v)?", g_u_plus_v == g_u_plus_g_v)
print("g(c * u) == c * g(u)?", g_cu == c_g_u)

g(u + v) == g(u) + g(v)? False
g(c * u) == c * g(u)? False


In [47]:
import numpy as np
theta_deg = 45
theta = np.radians(theta_deg)
P = np.array([[np.cos(theta), np.sin(theta)],
              [-np.sin(theta), np.cos(theta)]])
X = np.array([[2], [3]])
X_new = P @ X
print("Toạ độ điểm sau khi biến đổi (trong cơ sở xoay):")
print(X_new)

Toạ độ điểm sau khi biến đổi (trong cơ sở xoay):
[[3.53553391]
 [0.70710678]]


In [48]:
import sympy as sp
def T(v1, v2):
    return (v1 - v2, v1 + 2*v2)
u = sp.Matrix([1, 2])
v = sp.Matrix([3, -1])
c = 4
T_u = sp.Matrix(T(*u))
T_v = sp.Matrix(T(*v))
T_u_plus_v = sp.Matrix(T(*(u + v)))
T_u_plus_T_v = T_u + T_v
T_cu = sp.Matrix(T(*(c * u)))
c_T_u = c * T_u
print("T(u + v) == T(u) + T(v)?", T_u_plus_v == T_u_plus_T_v)
print("T(c * u) == c * T(u)?", T_cu == c_T_u)

T(u + v) == T(u) + T(v)? True
T(c * u) == c * T(u)? True


In [49]:
import sympy as sp
import numpy as np
a, b, c = 13, -10, 13
A = sp.Matrix([[a, b/2],
               [b/2, c]])
eigenvals = A.eigenvals()
print("Trị riêng λ1, λ2 là:")
sp.pprint(eigenvals)
A_np = np.array([[a, b/2], [b/2, c]])
eigvals, eigvecs = np.linalg.eigh(A_np)
theta_rad = np.arctan2(eigvecs[1, 0], eigvecs[0, 0])
theta_deg = np.degrees(theta_rad)
print(f"Góc xoay là: {theta_deg:.2f} độ")

Trị riêng λ1, λ2 là:
{8.0: 1, 18.0: 1}
Góc xoay là: -135.00 độ


In [50]:
import numpy as np
import sympy as sp
a, b, c = 13, -10, 13
d, e, f = 0, 0, -72
A = np.array([[a, b/2], [b/2, c]])
eigvals, eigvecs = np.linalg.eigh(A)
print("Trị riêng (λ1, λ2):", eigvals)
theta = np.arctan2(eigvecs[1, 0], eigvecs[0, 0])
theta_deg = np.degrees(theta)
print(f"Góc xoay: {theta_deg:.2f} độ")
x, y = sp.symbols('x y')
cos_theta = sp.sqrt(2)/2
sin_theta = cos_theta
x_new = cos_theta * x - sin_theta * y
y_new = sin_theta * x + cos_theta * y
expr = 13 * x**2 - 10 * x * y + 13 * y**2 - 72
expr_rotated = expr.subs({x: x_new, y: y_new})
expr_rotated = sp.simplify(expr_rotated)
print("Phương trình sau khi xoay:")
sp.pprint(expr_rotated)
expr_normalized = sp.Eq(expr_rotated, 0)
sp.pprint(expr_normalized)

Trị riêng (λ1, λ2): [ 8. 18.]
Góc xoay: -135.00 độ
Phương trình sau khi xoay:
          2                                                    2     
13⋅(x + y)    5⋅√2⋅(x + y)⋅(-x + √2⋅x - y)   13⋅(-x + √2⋅x - y)      
─────────── - ──────────────────────────── + ─────────────────── - 72
     2                     2                          4              
          2                                                    2         
13⋅(x + y)    5⋅√2⋅(x + y)⋅(-x + √2⋅x - y)   13⋅(-x + √2⋅x - y)          
─────────── - ──────────────────────────── + ─────────────────── - 72 = 0
     2                     2                          4                  
