BÀI THI THỬ

In [1]:
import numpy as np
# Câu 1a: Phép toán với vector
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
tong = A + B
bieu_thuc = 3*A - 2*B
print("Câu 1a:")
print("Tổng A + B:", tong)
print("Biểu thức 3A - 2B:", bieu_thuc)

Câu 1a:
Tổng A + B: [3 3 1 5]
Biểu thức 3A - 2B: [  4 -11  13 -10]


In [2]:
# Câu 1b: Tích vô hướng và góc
tich_vo_huong = np.dot(A, B)
do_dai_A = np.linalg.norm(A)
do_dai_B = np.linalg.norm(B)
cos_goc = tich_vo_huong / (do_dai_A * do_dai_B)
goc_do = np.degrees(np.arccos(cos_goc))
print("\nCâu 1b:")
print("Tích vô hướng A · B:", tich_vo_huong)
print("Góc giữa A và B (độ):", goc_do)


Câu 1b:
Tích vô hướng A · B: -8
Góc giữa A và B (độ): 108.3755542856849


In [3]:
# Câu 1c: Tính C^T C
C = np.array([[1, 2, -1], [0, 3, 4], [2, -1, 0]])
CTC = np.dot(C.T, C)
print("\nCâu 1c:")
print("Ma trận C^T C:")
print(CTC)


Câu 1c:
Ma trận C^T C:
[[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [4]:
# Câu 2a: Nhân ma trận
M = np.array([[1,2,3,0],[4,5,6,1],[7,8,9,2],[0,1,1,0]])
N = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
tich_MN = np.dot(M, N)
print("\nCâu 2a:")
print("Tích M × N:")
print(tich_MN)


Câu 2a:
Tích M × N:
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]


In [5]:
# Câu 2b: Định thức
dinh_thuc_M = np.linalg.det(M)
print("\nCâu 2b:")
print("Định thức của M:", dinh_thuc_M)


Câu 2b:
Định thức của M: 6.66133814775094e-16


In [6]:
# Câu 2c: Hạng
hang_N = np.linalg.matrix_rank(N)
print("\nCâu 2c:")
print("Hạng của N:", hang_N)


Câu 2c:
Hạng của N: 2


In [7]:
# Câu 3a: Nghịch đảo ma trận
P = np.array([[2,1,0,1],[0,3,1,-1],[1,0,4,2],[0,1,0,3]])
P_nghich = np.linalg.inv(P)
print("\nCâu 3a:")
print("Ma trận nghịch đảo của P:")
print(P_nghich)


Câu 3a:
Ma trận nghịch đảo của P:
[[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]


In [8]:
# Câu 3b: Giải hệ Px = b
b = np.array([4,7,9,5])
x = np.dot(P_nghich, b)
print("\nCâu 3b:")
print("Nghiệm x của hệ Px = b:")
print(x)


Câu 3b:
Nghiệm x của hệ Px = b:
[0.46511628 2.10465116 1.65116279 0.96511628]


In [9]:
# Câu 3c: Kiểm tra nghiệm
kiem_tra = np.dot(P, x)
print("\nCâu 3c:")
print("Kiểm tra P · x có bằng b không:")
print("P · x =", kiem_tra)
print("b =", b)


Câu 3c:
Kiểm tra P · x có bằng b không:
P · x = [4. 7. 9. 5.]
b = [4 7 9 5]


In [10]:
# Câu 4: Giá trị riêng và vector riêng
Q = np.array([[4, -1, 0], [1, 3, -2], [0, 1, 2]])
gia_tri_rieng, vector_rieng = np.linalg.eig(Q)
vector_chuan = vector_rieng / np.linalg.norm(vector_rieng, axis=0)
print("\nCâu 4:")
print("Giá trị riêng:")
print(gia_tri_rieng)
print("Vector riêng:")
print(vector_rieng)
print("Vector riêng đã chuẩn hóa:")
print(vector_chuan)


Câu 4:
Giá trị riêng:
[3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]
Vector riêng:
[[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]
Vector riêng đã chuẩn hóa:
[[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743+0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]


In [11]:
# Câu 5: Ứng dụng thực tế
R = np.array([[1,-2,3],[2,0,1],[-1,1,4]])
b = np.array([10,8,7])
x = np.linalg.solve(R, b)
print("\nCâu 5a:")
print("Nghiệm x của hệ Rx = b:")
print(x)


Câu 5a:
Nghiệm x của hệ Rx = b:
[2.7826087  0.04347826 2.43478261]


In [12]:
# Câu 5b: Giải lại bằng nghịch đảo
R_nghich = np.linalg.inv(R)
x2 = np.dot(R_nghich, b)
print("\nCâu 5b:")
print("Nghiệm x2 bằng nghịch đảo:")
print(x2)


Câu 5b:
Nghiệm x2 bằng nghịch đảo:
[2.7826087  0.04347826 2.43478261]


In [13]:
# Câu 5c: Chuẩn Frobenius
chuan_fro = np.linalg.norm(R, 'fro')
print("\nCâu 5c:")
print("Chuẩn Frobenius của R:", chuan_fro)


Câu 5c:
Chuẩn Frobenius của R: 6.082762530298219
