**BÀI TRÊN LỚP**

In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
tich = np.inner(a, b)
print(tich)

32


In [2]:
print(np.dot(a,b))

32


In [3]:
import numpy as np
a = np.array([1,2,-3])
np.linalg.norm(a)

np.float64(3.7416573867739413)

In [4]:
a = np.array([1,2,-3])
np.linalg.norm(a,1)

np.float64(6.0)

In [8]:
import math
import numpy as np
def chuan(a, n):
    return np.linalg.norm(a, ord=n)
a = np.array([1, 2, -3])
print(chuan(a, 1))
print(np.linalg.norm(a, 1))
print(chuan(a, 2))
print(np.linalg.norm(a, 2))
print(chuan(a, 3))
print(np.linalg.norm(a, 3))
print(chuan(a, 1000))
print(np.linalg.norm(a, 1000))

6.0
6.0
3.7416573867739413
3.7416573867739413
3.3019272488946263
3.3019272488946263
inf
inf


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


In [9]:
from scipy import linalg
print(linalg.norm(a))
print(linalg.norm(a, 100))
print(linalg.norm(a, 1000))

3.7416573867739413
3.0
inf


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


In [10]:
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
print(MT)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]


In [11]:
v = (1.0/m)*MT.dot(mi)
print (v)

[1.3 0.9 0. ]


In [13]:
import numpy as np
A = np.array([[0.998, 0.136],
              [-0.002, 0.864]])
A_100 = np.eye(2)
for _ in range(100):
    A_100 = np.dot(A_100, A)
v0 = np.array([[0.95],
               [0.05]])
v100 = np.dot(A_100, v0)
print("Ma trận A^100:")
print(A_100)
print("Vector trạng thái sau 100 tuần:")
print(v100)

Ma trận A^100:
[[ 0.67622106  0.69703713]
 [-0.01025055 -0.01056553]]
Vector trạng thái sau 100 tuần:
[[ 0.67726186]
 [-0.0102663 ]]


In [14]:
import numpy as np
A = np.array([[1, -68],
              [1, 1]])
b = np.array([0, 1])
solution = np.linalg.solve(A, b)
print("Nghiệm của hệ phương trình là:")
print(f"x = {solution[0]}")
print(f"y = {solution[1]}")

Nghiệm của hệ phương trình là:
x = 0.9855072463768116
y = 0.014492753623188406


In [15]:
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y]) # khai báo vector: (x, y)T
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v]) # phương trình được chuyển về 1 phía
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [16]:
import numpy as np
A = np.array([[1, 6],
              [5, 2]])
u = np.array([[6],
              [-5]])
Au = np.dot(A, u)
lambda_u = -4 * u
print("Au =")
print(Au)
print("-4u =")
print(lambda_u)
print("Kiểm tra Au == -4u:")
print(np.allclose(Au, lambda_u))

Au =
[[-24]
 [ 20]]
-4u =
[[-24]
 [ 20]]
Kiểm tra Au == -4u:
True


In [17]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

[-7.000, 3.000]


In [18]:
print (sympy.pretty(nghiem))

[-7, 3]


In [19]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P) # tính giá trị nghịch đảo của P
print (P1)

[[-0.3  0.9]
 [ 0.3  0.1]]


In [21]:
print(A.dot(P))

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [20]:
print(P.dot(D))

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [22]:
print(P @ (D ** 1000) @ P1 )

[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]


In [23]:
print (D **2)

[[49  0]
 [ 0  9]]


BT VỀ NHÀ

Câu 1: [Trắc nghiệm] Trong Python 3, các câu lệnh sau đây, câu lệnh nào tính chuẩn 2 của
vector a. Với a được xác định là:
import numpy as np
a = np.array([1,2,3])
a. >>> mag = np.sqrt(a.dot(a))
b. >>> mag = np.sqrt(a @ a )
c. >>> mag = np.sqrt(np.inner(a,a))
d. >>> mag = lambda x : math.sqrt(sum(i** 2 for i in x))mag(a)

Đáp án đúng: a

In [24]:
import numpy as np
def vector_distance(u, v):
    return np.linalg.norm(u - v)
def vector_angle(u, v):
    cos_theta = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
    return np.arccos(cos_theta)
def orthogonal_projection(u, v):
    return (np.dot(u, v) / np.dot(v, v)) * v
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
distance = vector_distance(u, v)
angle = vector_angle(u, v)
projection = orthogonal_projection(u, v)
print(f"a/ Khoảng cách giữa u và v: {distance}")
print(f"b/ Góc giữa u và v: {np.degrees(angle)} độ")
print(f"c/ Phép chiếu trực giao của u lên v: {projection}")


a/ Khoảng cách giữa u và v: 5.196152422706632
b/ Góc giữa u và v: 12.933154491899135 độ
c/ Phép chiếu trực giao của u lên v: [1.66233766 2.07792208 2.49350649]
