In [22]:
import numpy as np
D = np.array([[1,2],[3,4]])
np.copyto(E, D)

In [23]:
import numpy as np
E = np.array([[1,2],[3,5]])
np.copyto(E, D)

In [24]:
print(E)

[[1 2]
 [3 4]]


In [27]:
import numpy as np
x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'
C = np.array([[x, y], [1, 2]], dtype=object)
print(C)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


In [28]:
A = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])


ValueError: matrix must be 2-dimensional

In [29]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
from numpy import matlib
G = matlib.identity(5) # cú pháp: matlib.identity(n)
print (G)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
H = matlib.randn(3,2) # cú pháp: matlib.randn(*args)
print(H)

[[-0.73858042 -0.97733389]
 [ 1.3318182  -0.84844519]
 [-1.53932418 -1.45564439]]


In [32]:
K = matlib.zeros([4,4]) #  cú pháp: matlib.zeros(shape)
print(K)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2] # thử chạy nhiều lần với dãy c dài khác nhau!
M = np.asmatrix([[1,2],[3,4]]) # khởi tạo ma trận 2x2
for i in range(len(c)):
 ci = np.asmatrix([[1,1],[1,0]])
 ci[0, 0] = c[i]
 if (i==0):
    M = ci
 else:
    M = M.dot(ci)
print(M)
print(M[0,0]/M[1,0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [42]:
import numpy as np
X = np.array([[1,1],[1,2],[1,3],[1,4],[1,5]])
Y = np.array([[1],[2],[4],[4],[6]])
XT = X.T
A1 = np.linalg.inv(XT @ X)
A2 = XT @ Y
A = A1 @ A2
print("Hệ số hồi quy:")
print("a =", A[0,0])
print("b =", A[1,0])

Hệ số hồi quy:
a = -0.19999999999999662
b = 1.2000000000000008


In [50]:
def bpcuctieu(a):
  b = []
  o1 = []
  for i in range(len(a)):
    o1.append(1.0)
    b.append((i+1)*1.0)
  x = np.array([o1, b])
  u = np.dot(x, x.T)
  y = np.array(a)
  from numpy import linalg
  u_1 =np.linalg.inv(u)
  v = np.dot(u_1, x)
  A = np.dot(v, y)
  return A
print(bpcuctieu([10.0, 8,7,5,2]))

[12.1 -1.9]
