In [2]:
import numpy as np
import math
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])
sum_AB = A + B
expr = 2 * A + 3 * B
print("a) A + B =", sum_AB)
print("   2A + 3B =", expr)
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_deg = math.degrees(math.acos(cos_theta))
print("\nb) A · B =", dot_product)
print("   Góc giữa A và B =", round(angle_deg, 3), "độ")
C_transpose = C.T
product = np.dot(C, C_transpose)
print("\nc) C * C^T =")
print(product)

a) A + B = [2 3 1 6]
   2A + 3B = [ 3 11  2 14]

b) A · B = -5
   Góc giữa A và B = 99.594 độ

c) C * C^T =
[[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [3]:
import numpy as np
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])
N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])
product = np.dot(M, N)
print("a) M × N =")
print(product)
if M.shape[0] == M.shape[1]:
    det_M = np.linalg.det(M)
    print("\nb) Định thức của M =", round(det_M, 3))
else:
    print("\nb) Không thể tính định thức vì M không phải là ma trận vuông.")
rank_N = np.linalg.matrix_rank(N)
print("\nc) Hạng của ma trận N =", rank_N)

a) M × N =
[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b) Định thức của M = 409.0

c) Hạng của ma trận N = 4


In [5]:
import numpy as np
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])
b = np.array([6, 8, 3, 7])
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P:")
    print(np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch.")
x = np.dot(P_inv, b)
print("\nb) Nghiệm của hệ phương trình:")
print(np.round(x, 3))
b_check = np.dot(P, x)
print("\nc) Kiểm tra P * x:")
print(np.round(b_check, 3))
print("So sánh với vector b gốc:", b)

a) Ma trận nghịch đảo của P:
[[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]

b) Nghiệm của hệ phương trình:
[2.    1.714 0.429 0.857]

c) Kiểm tra P * x:
[6. 8. 3. 7.]
So sánh với vector b gốc: [6 8 3 7]


In [4]:
import numpy as np
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("a) Các giá trị riêng của Q:")
print(np.round(eigenvalues, 3))
print("\nb) Các vector riêng (cột, chưa chuẩn hóa):")
print(np.round(eigenvectors, 3))
normalized_vectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print("\nc) Các vector riêng đã chuẩn hóa:")
print(np.round(normalized_vectors, 3))


a) Các giá trị riêng của Q:
[6.355+0.j    2.822+1.077j 2.822-1.077j]

b) Các vector riêng (cột, chưa chuẩn hóa):
[[ 0.748+0.j    -0.374+0.342j -0.374-0.342j]
 [-0.189+0.j     0.095+0.574j  0.095-0.574j]
 [ 0.636+0.j     0.636+0.j     0.636-0.j   ]]

c) Các vector riêng đã chuẩn hóa:
[[ 0.748+0.j    -0.374+0.342j -0.374-0.342j]
 [-0.189+0.j     0.095+0.574j  0.095-0.574j]
 [ 0.636+0.j     0.636+0.j     0.636-0.j   ]]


In [6]:
import numpy as np
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])
x = np.linalg.solve(R, b)
print("a) Nghiệm của hệ Rx = b là:")
print(np.round(x, 3))
try:
    R_inv = np.linalg.inv(R)
    x_inv = np.dot(R_inv, b)
    print("\nb) Ma trận R khả nghịch.")
    print("   Nghiệm tìm bằng R⁻¹ * b là:")
    print(np.round(x_inv, 3))
    print("   So sánh với np.linalg.solve:", np.allclose(x, x_inv))
except np.linalg.LinAlgError:
    print("\nb) Ma trận R không khả nghịch.")
fro_norm = np.linalg.norm(R, 'fro')
print("\nc) Chuẩn Frobenius của ma trận R là:", round(fro_norm, 3))

a) Nghiệm của hệ Rx = b là:
[2.788 1.529 1.188]

b) Ma trận R khả nghịch.
   Nghiệm tìm bằng R⁻¹ * b là:
[2.788 1.529 1.188]
   So sánh với np.linalg.solve: True

c) Chuẩn Frobenius của ma trận R là: 8.0
