In [ ]:
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b)
C = np.asmatrix(np.random.random( (10,5) ) )
D = np.asmatrix([ [4, 3], [2, 6] ])
F = np.eye(3, k=1)
F1 = np.eye(3, k=0)
F2 = np.eye(3, k=-1)
E = np.array([1, 2, 3]).reshape(-1, 1)
print("1/",a)
print("2/",b)
print("3/",c)
print("4/",A)
print("5/",B)
print("6/",C)
print("7/",D)
print("8/",F)
print("9/",F1)
print("10/",F2)
print("11/",np.linalg.matrix_rank(C))
print("12/",A.I)
print("13/",linalg.inv(A))
print("14/",linalg.det(A))
print("15/",A.T)
print("16/",A.H)
print("17/",linalg.solve(A, b))
print("18/",np.asmatrix(a).T )
print("19/",linalg.lstsq(F, E))
print("20/",np.add(A, D))
print("21/",np.subtract(A, D))
print("22/",np.divide(A, D) )
print("23/",A @ D )
print("24/",np.multiply(D, A))
print("25/",np.dot(A, D))
print("26/",np.vdot(A, D))
print("27/",linalg.expm(A))
print("28/",linalg.logm(A))

1/ [1 2 3]
2/ [[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
3/ [[[ 0.5  1.5 10. ]
  [ 3.   2.   1. ]]

 [[ 6.   5.   4. ]
  [ 7.   8.   9. ]]]
4/ [[0.6626619  0.548989  ]
 [0.38037059 0.51277982]]
5/ [[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
6/ [[0.32122363 0.11121146 0.43660941 0.43703246 0.07160009]
 [0.50197976 0.51525428 0.05038205 0.10604328 0.38234218]
 [0.68401699 0.84486267 0.73894573 0.93549753 0.52321098]
 [0.31525724 0.22865047 0.56675212 0.90384669 0.84271302]
 [0.26846254 0.1461211  0.7963043  0.96409869 0.02862707]
 [0.35124565 0.99700724 0.61488416 0.75803492 0.11315082]
 [0.09288579 0.20929659 0.89042993 0.36541763 0.52924679]
 [0.88063574 0.84714855 0.21720777 0.48525095 0.76152441]
 [0.56370255 0.77725717 0.00839333 0.3033376  0.70502884]
 [0.17898459 0.17723098 0.2696624  0.62422267 0.48126301]]
7/ [[4 3]
 [2 6]]
8/ [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
9/ [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
10/ [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
11/ 5
12/ [[ 3.91493604 -

In [ ]:
from scipy import linalg
import numpy as np
A = np.array([ [0,1], [1,0]])
print("1/",A)
temp = A.dot(A)
print("2/",temp)
k = 6
for i in range(k-1):
 temp = temp.dot(A)
 print ("3/",temp)
 print('---')
 B = np.array([ [0,-1], [-1,0]])
 print("4/",B)
 temp = B.dot(B)
 print("5/",temp)


1/ [[0 1]
 [1 0]]
2/ [[1 0]
 [0 1]]
3/ [[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]
3/ [[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
3/ [[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]
3/ [[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
3/ [[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]


In [ ]:
from scipy import linalg
import numpy as np
k = 5
for i in range(k-1):
  temp = temp.dot(B)
  print ("6/",temp)
  print('---')
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print("7/",C)
temp = C.dot(C) # tính toan lần thứ 1
print("8/",temp)
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print("9/",temp)
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print("10/",temp)
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print ("11/",MM)
MM = M.dot(M) # tính M3
print ("12/",MM)
for i in range(100): # tính các M^ khác.
 MM = MM.dot(M)
print ("13/",MM)


6/ [[-1  0]
 [ 0 -1]]
---
6/ [[0 1]
 [1 0]]
---
6/ [[-1  0]
 [ 0 -1]]
---
6/ [[0 1]
 [1 0]]
---
7/ [[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
8/ [[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
9/ [[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
10/ [[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
11/ [[0.7  0.45]
 [0.3  0.55]]
12/ [[0.7  0.45]
 [0.3  0.55]]
13/ [[0.6 0.6]
 [0.4 0.4]]


In [ ]:
from scipy import linalg
import numpy as np
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M)
print ("1/",P)
print ("2/",L)
print ("3/",U)
print("4/",P @ L @ U)


1/ [[1. 0.]
 [0. 1.]]
2/ [[1.   0.  ]
 [0.25 1.  ]]
3/ [[0.8   0.3  ]
 [0.    0.625]]
4/ [[0.8 0.3]
 [0.2 0.7]]


In [ ]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A)
print("1/",temp)
temp = temp.dot(A)
print("2/",temp)
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
 temp = temp.dot(A)
 sumA = sumA + temp
print ("3/",temp)
print ("4/",sumA)

1/ [[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
2/ [[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
3/ [[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
4/ [[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


In [1]:
import numpy as np
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])
print("Ma trận A:")
print(A)
det_A = np.linalg.det(A)
print(f"Định thức của A: {det_A}")
assert det_A != 0, "Ma trận không khả nghịch!"
text = "NguyenVanA"
print(f"Chuỗi gốc: {text}")
def text_to_vector(text):
    vec = [ord(c) for c in text]
    while len(vec) % 3 != 0:
        vec.append(0)
    return np.array(vec).reshape(-1, 3).T
P = text_to_vector(text)
print("Vector P (mã ASCII):")
print(P)
C = A @ P
print("Bản mã C:")
print(C)
A_inv = np.linalg.inv(A)
P_decoded = A_inv @ C
decoded_text = ''.join([chr(round(num)) for num in P_decoded.T.flatten() if round(num) > 0])
print("Giải mã văn bản:")
print(decoded_text)
import numpy as np
def continued_fraction_pq(coeffs):
    print(f"Chuỗi hệ số: {coeffs}")
    M = np.array([[coeffs[0], 1],
                  [1, 0]])
    print(f"M0:\n{M}")

    for i, c in enumerate(coeffs[1:], 1):
        M_step = np.array([[c, 1],
                           [1, 0]])
        print(f"Bước {i}: Nhân với\n{M_step}")
        M = M @ M_step
        print(f"Kết quả sau bước {i}:\n{M}")
    result = M @ np.array([1, 0])
    pn, qn = result
    print(f"p_n = {pn}, q_n = {qn}")
    return pn, qn
coeffs = [3, 1, 2]
pn, qn = continued_fraction_pq(coeffs)
print(f"\n=> Phân số: {pn}/{qn} = {pn / qn}")


Ma trận A:
[[2 1 1]
 [1 3 2]
 [1 0 0]]
Định thức của A: -1.0
Chuỗi gốc: NguyenVanA
Vector P (mã ASCII):
[[ 78 121  86  65]
 [103 101  97   0]
 [117 110 110   0]]
Bản mã C:
[[376 453 379 130]
 [621 644 597  65]
 [ 78 121  86  65]]
Giải mã văn bản:
NguyenVanA
Chuỗi hệ số: [3, 1, 2]
M0:
[[3 1]
 [1 0]]
Bước 1: Nhân với
[[1 1]
 [1 0]]
Kết quả sau bước 1:
[[4 3]
 [1 1]]
Bước 2: Nhân với
[[2 1]
 [1 0]]
Kết quả sau bước 2:
[[11  4]
 [ 3  1]]
p_n = 11, q_n = 3

=> Phân số: 11/3 = 3.6666666666666665


In [ ]:
from fractions import Fraction

def continued_fraction(x):
    cf = []
    while x.denominator != 1:
        q = x.numerator // x.denominator
        cf.append(q)
        x = Fraction(x.denominator, x.numerator - q * x.denominator)
    cf.append(x.numerator)
    return cf
f = Fraction(43, 30)
cf = continued_fraction(f)
print("Phân số liên tục của 43/30 là:", cf)


Phân số liên tục của 43/30 là: [1, 2, 3, 4]
